"""Off-policy actor-critic losses: V-trace, TD(lambda) and UPGO.

AlphaStar's learner is off-policy -- trajectories are generated by a slightly
older actor than the one being updated -- so the corrections here are not
optional garnish, they are what makes the update valid at all:

  * V-trace  (Espeholt et al. 2018) clipped importance sampling for the value
             target and the policy gradient
  * TD(lambda)  value target that trades bias against variance
  * UPGO     self-imitation: push the policy toward trajectories that turned out
             better than the critic expected, ignore the ones that turned out
             worse

All functions take time-major tensors [T, M]: T unroll steps, M drone-sequences.
Values carry one extra step, [T+1, M], for bootstrapping.
"""
from __future__ import annotations

import torch
from torch import Tensor


def _check(x: Tensor, T: int, M: int, name: str):
    if tuple(x.shape) != (T, M):
        raise ValueError(f"{name} must be [T={T}, M={M}], got {tuple(x.shape)}")


@torch.no_grad()
def vtrace_returns(log_rho: Tensor, rewards: Tensor, values: Tensor,
                   discounts: Tensor, rho_bar: float = 1.0,
                   c_bar: float = 1.0) -> tuple[Tensor, Tensor]:
    """V-trace targets and the policy-gradient advantage.

    log_rho   [T,M]   log pi(a|s) - log mu(a|s)   (target minus behaviour)
    rewards   [T,M]
    values    [T+1,M] critic estimates, last entry is the bootstrap
    discounts [T,M]   gamma, zeroed at episode boundaries

    Returns (vs, pg_advantage), both [T,M].
    """
    T, M = rewards.shape
    _check(log_rho, T, M, "log_rho")
    _check(discounts, T, M, "discounts")
    if values.shape != (T + 1, M):
        raise ValueError(f"values must be [T+1={T+1}, M={M}], got {tuple(values.shape)}")

    rho = log_rho.exp()
    clipped_rho = rho.clamp(max=rho_bar)
    clipped_c = rho.clamp(max=c_bar)

    # delta_t V = rho_t * (r_t + gamma * V_{t+1} - V_t)
    deltas = clipped_rho * (rewards + discounts * values[1:] - values[:-1])

    # v_s = V_s + delta_s + gamma * c_s * (v_{s+1} - V_{s+1}), solved backwards
    acc = torch.zeros(M, device=rewards.device, dtype=rewards.dtype)
    out = torch.zeros_like(rewards)
    for t in range(T - 1, -1, -1):
        acc = deltas[t] + discounts[t] * clipped_c[t] * acc
        out[t] = acc
    vs = out + values[:-1]

    # advantage uses v_{s+1}, so shift the targets and bootstrap the tail
    vs_next = torch.cat([vs[1:], values[-1:]], dim=0)
    pg_adv = clipped_rho * (rewards + discounts * vs_next - values[:-1])
    return vs, pg_adv


@torch.no_grad()
def td_lambda_returns(rewards: Tensor, values: Tensor, discounts: Tensor,
                      lam: float = 0.8) -> Tensor:
    """G^lambda_t = r_t + gamma[(1-lam) V_{t+1} + lam G^lambda_{t+1}]."""
    T, M = rewards.shape
    acc = values[-1]
    out = torch.zeros_like(rewards)
    for t in range(T - 1, -1, -1):
        acc = rewards[t] + discounts[t] * ((1 - lam) * values[t + 1] + lam * acc)
        out[t] = acc
    return out


@torch.no_grad()
def upgo_returns(rewards: Tensor, values: Tensor, discounts: Tensor) -> Tensor:
    """Upgoing return -- AlphaStar's self-imitation signal.

        G_t = r_t + gamma * ( G_{t+1}  if Q_{t+1} >= V_{t+1} else V_{t+1} )

    Bootstraps from the *better* of the trajectory and the critic, so the policy
    is pulled toward outcomes that beat expectation and is not dragged down by
    the ones that did not.
    """
    T, M = rewards.shape
    out = torch.zeros_like(rewards)
    acc = values[-1]                       # bootstrap for the final step
    for t in range(T - 1, -1, -1):
        if t == T - 1:
            nxt = values[t + 1]            # nothing after the unroll to imitate
        else:
            # compare the NEXT step's Q against the NEXT step's V
            q_next = rewards[t + 1] + discounts[t + 1] * values[t + 2]
            nxt = torch.where(q_next >= values[t + 1], acc, values[t + 1])
        acc = rewards[t] + discounts[t] * nxt
        out[t] = acc
    return out


# ------------------------------------------------------------ head utilities
def multi_head_logp(logits: dict[str, Tensor], actions: dict[str, Tensor],
                    heads: tuple[str, ...], batch_ndim: int = 1) -> Tensor:
    """log pi(a|s) for a factorised autoregressive action.

    The chain rule makes this an exact joint log-probability, not an
    approximation: log pi(a) = sum_h log pi_h(a_h | a_<h), and each head was
    already conditioned on the sampled prefix.
    """
    total = None
    for h in heads:
        lg, a = logits[h].float(), actions[h]
        lp = torch.log_softmax(lg, dim=-1)
        g = lp.gather(-1, a.unsqueeze(-1)).squeeze(-1)      # shape == a.shape
        # heads may carry extra axes beyond the batch (comms: 8 tokens); those
        # are part of one joint action, so they sum
        while g.dim() > batch_ndim:
            g = g.sum(-1)
        total = g if total is None else total + g
    return total


def multi_head_entropy(logits: dict[str, Tensor], heads: tuple[str, ...],
                       batch_ndim: int = 1) -> Tensor:
    """Summed per-head entropy. Masked logits contribute ~0, as they should."""
    total = None
    for h in heads:
        lg = logits[h].float()
        lp = torch.log_softmax(lg, dim=-1)
        e = -(lp.exp() * lp).sum(-1)
        while e.dim() > batch_ndim:
            e = e.sum(-1)
        total = e if total is None else total + e
    return total


def policy_gradient_loss(logp: Tensor, advantage: Tensor,
                         mask: Tensor | None = None) -> Tensor:
    adv = advantage.detach()
    loss = -logp * adv
    if mask is not None:
        return (loss * mask).sum() / mask.sum().clamp_min(1.0)
    return loss.mean()


def value_loss(values: Tensor, targets: Tensor,
               mask: Tensor | None = None) -> Tensor:
    l = 0.5 * (values - targets.detach()).pow(2)
    if mask is not None:
        return (l * mask).sum() / mask.sum().clamp_min(1.0)
    return l.mean()
